### ISSUE TITLE
Deprecated Sphinx methods: add_javascript() and add_stylesheet()

### ISSUE THREAD

**Issue by ScriptAutomate** [ulrobix/sphinxcontrib-contentui#10]
`add_javascript()` and `add_stylesheet()` are deprecated Sphinx methods, and should be updated to remove any RemovedInSphinx warning messages when building.

- Sphinx 3.x.x will show RemovedInSphinx warning messages about deprecation, but both the old format and expected format will work either way.
- Sphinx 4.x.x will be dropping all support for `.add_javascript()` and `.add_stylesheet()`, moving to `.add_js_file()` and `.add_css_file()`. The old format will no longer work in Sphinx 4.x.x.
- These changes happened back in 1.8, so should work with sphinx>=1.8.0
  - [Sphinx Docs: add_js_file](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file)
  - [Sphinx Docs: add_css_file](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file)

**Comment by ulrobix** [comment]
Merged
