### ISSUE TITLE
What is your license?

### ISSUE THREAD

**Issue by gregelin** [ulrobix/sphinxcontrib-contentui#4]
@khaliullov @ulrobix - Was very excited to find your project. Adding tabs to display the install directions for our open source software greatly improves readability. Thank you!

Have you considered adding a license to your software? It would be really useful so we knew we're using sphinxcontrib-contenui as intended!

**Comment by ulrobix** [comment]
Hi, MIT. 
You are welcome.

**Comment by gregelin** [comment]
Thanks for adding license!
